
services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile.dev
    ports:
      - "3333:3333"
    volumes:
      - ./packages/shared:/app/packages/shared
      - ./packages/api:/app/packages/api
    env_file:
      - packages/api/.env
    depends_on:
      postgres:
        condition: service_healthy

  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./packages/shared:/app/packages/shared
      - ./packages/web:/app/packages/web
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3333

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=adonis_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 