services:
  app:
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    volumes:
      - ./packages/api:/app/packages/api
      - ./packages/web:/app/packages/web
    ports:
      - "3333:3333"
      - "5173:5173"
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=adonis_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 