// @ts-nocheck
/* eslint-disable */
// --------------------------------------------------
// This file is auto-generated by Tuyau. Do not edit manually !
// --------------------------------------------------

import type { MakeTuyauRequest, MakeTuyauResponse } from '@tuyau/utils/types'
import type { InferInput } from '@vinejs/vine/types'

type UsersGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/users_controller.ts').default['index'], false>
}
type UsersCreateGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/users_controller.ts').default['create'], false>
}
type UsersPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/user_validator.ts')['createUserValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/users_controller.ts').default['store'], true>
}
type UsersIdGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/users_controller.ts').default['show'], false>
}
type UsersIdEditGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/users_controller.ts').default['edit'], false>
}
type UsersIdPutPatch = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/users_controller.ts').default['update'], false>
}
type UsersIdDelete = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/users_controller.ts').default['destroy'], false>
}
type UsersFindbyemailPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/users_controller.ts').default['findByEmail'], false>
}
type UsersFindbynamePost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/users_controller.ts').default['findByName'], false>
}
export interface ApiDefinition {
  'users': {
    '$url': {
    };
    '$get': UsersGetHead;
    '$head': UsersGetHead;
    'create': {
      '$url': {
      };
      '$get': UsersCreateGetHead;
      '$head': UsersCreateGetHead;
    };
    '$post': UsersPost;
    ':id': {
      '$url': {
      };
      '$get': UsersIdGetHead;
      '$head': UsersIdGetHead;
      'edit': {
        '$url': {
        };
        '$get': UsersIdEditGetHead;
        '$head': UsersIdEditGetHead;
      };
      '$put': UsersIdPutPatch;
      '$patch': UsersIdPutPatch;
      '$delete': UsersIdDelete;
    };
    'findByEmail': {
      '$url': {
      };
      '$post': UsersFindbyemailPost;
    };
    'findByName': {
      '$url': {
      };
      '$post': UsersFindbynamePost;
    };
  };
}
const routes = [
  {
    params: [],
    name: 'users.index',
    path: '/users',
    method: ["GET","HEAD"],
    types: {} as UsersGetHead,
  },
  {
    params: [],
    name: 'users.create',
    path: '/users/create',
    method: ["GET","HEAD"],
    types: {} as UsersCreateGetHead,
  },
  {
    params: [],
    name: 'users.store',
    path: '/users',
    method: ["POST"],
    types: {} as UsersPost,
  },
  {
    params: ["id"],
    name: 'users.show',
    path: '/users/:id',
    method: ["GET","HEAD"],
    types: {} as UsersIdGetHead,
  },
  {
    params: ["id"],
    name: 'users.edit',
    path: '/users/:id/edit',
    method: ["GET","HEAD"],
    types: {} as UsersIdEditGetHead,
  },
  {
    params: ["id"],
    name: 'users.update',
    path: '/users/:id',
    method: ["PUT","PATCH"],
    types: {} as UsersIdPutPatch,
  },
  {
    params: ["id"],
    name: 'users.destroy',
    path: '/users/:id',
    method: ["DELETE"],
    types: {} as UsersIdDelete,
  },
] as const;
export const api = {
  routes,
  definition: {} as ApiDefinition
}
